---
- name: apt-update
  apt:
  update_cache: yes
- name: Install Docker
  apt:
   name: docker.io
   state: present
- name: Create new directory
  file:
   path: /home/edureka/Downloads/dockDeploy
   state: directory
- name: Copy war file
  copy:
   src: /home/edureka/Downloads/addressbook.war
   dest: /home/edureka/Downloads/dockDeploy/
- name: Copy Dockerfile
  copy:
   src: /home/edureka/Downloads/Dockerfile
   dest: /home/edureka/Downloads/dockDeploy/
- name: Build Docker Image
  command: chdir=/home/edureka/Downloads/dockDeploy/ docker build . -t edureka/inclass
- name: Run Docker Container
  command: chdir=/home/edureka/Downloads/dockDeploy/ docker run -it -d -p 8085:8080 edureka/inclass